module.exports = {
  "docs": [
    {
      "items": [
        "How To Upload A File",
        "Retry Test Actions",
        "Build An Interactive Prompt",
        "Opt Out of AB Tests",
        "Work With Basic Auth",
        "Download Secure Files",
        "Take Screenshot on Failure",
        "Retrieve HTTP Status Codes",
        "How To Figure Out What to Update",
        "Data Driven Testing",
        "How To Download a File",
        "Choosing a Programming Language",
        "Locator Strategy",
        "Dynamic Pages",
        "REST APIs",
        "How To Work With Tables",
        "Cloud",
        "Chrome Driver",
        "Work With Frames",
        "Accessing Previous Tips Archive",
        "Selenium Resources",
        "How to Test HTML5 Drag and Drop",
        "Work With Multiple Windows",
        "Disabled Element",
        "How To Handle Exceptions",
        "How To Test Checkboxes",
        "Implicit vs Explicit Waits",
        "Load Testing",
        "How to Do Performance Testing",
        "Select From A Dropdown",
        "How To Work With Hovers",
        "How To Work With JavaScript Alerts",
        "How To Use Selenium Grid",
        "Growl",
        "Wrapper",
        "Junit XML",
        "Tagging",
        "List Tags",
        "How To Press Keyboard Keys",
        "Right Click",
        "Limit Bandwidth",
        "Highlight Elements",
        "Blacklist",
        "Broken Images",
        "Load Testing Revisited",
        "SafariDriver",
        "Use A Page Object",
        "The Mobile Testing Pyramid",
        "How To Run Your Tests Headlessly with Chrome",
        "Open a New Window or Tab",
        "Download A File Revisited",
        "Use A Base Page Object",
        "Template"
      ]
    }
  ]
};