name: Test Build
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - uses: actions/cache@v4
        id: cache-npm-packages
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install Dependencies
        if: steps.cache-npm-packages.outputs.cache-hit != 'true'
        run: |
          cd frontend
          npm install
      - uses: actions/cache@v4
        id: cache-build
        with:
          path: |
            frontend/build
          key: ${{ runner.os }}-${{ github.sha }}

      - name: Run Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          cd frontend
          npm run build
